#!/bin/sh
 while true;do
if [ $(busybox ps | grep ffmpeg | grep -v grep | awk '{print$1}' | wc -l) -lt 4 ]; then
ffmpeg -re -i "http://ngcdn001.cnr.cn/live/zgzs/index.m3u8" -ar 44100 -threads 1 -ac 1 -f mp3 "icecast://source:hackme@192.168.31.1:8001/zgzs1" && ffmpeg -re -i "http://ngcdn002.cnr.cn/live/jjzs/index.m3u8" -ar 44100 -threads 1 -ac 1 -f mp3 "icecast://source:hackme@192.168.31.1:8001/jjzs2" && ffmpeg -re -i "http://ngcdn003.cnr.cn/live/yyzs/index.m3u8" -ar 44100 -threads 1 -ac 1 -f mp3 "icecast://source:hackme@192.168.31.1:8001/yyzs3" && ffmpeg -re -i "http://ngcdn010.cnr.cn/live/wyzs/index.m3u8" -ar 44100 -threads 1 -ac 1 -f mp3 "icecast://source:hackme@192.168.31.1:8001/wyzs10"
else
echo Streaming succeeded
fi
sleep 5
done
