#!/bin/sh

m3u8list=$(cat /etc/m3u8list)
LAN=$(uci get network.lan.ipaddr)

ch1=$(sed -n '1p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch2=$(sed -n '2p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch3=$(sed -n '3p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch4=$(sed -n '4p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch5=$(sed -n '5p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch6=$(sed -n '6p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch7=$(sed -n '7p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch8=$(sed -n '8p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch9=$(sed -n '9p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch10=$(sed -n '10p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch11=$(sed -n '11p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch12=$(sed -n '12p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch13=$(sed -n '13p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch14=$(sed -n '14p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')
ch15=$(sed -n '15p' $m3u8list | sed 's/.m3u8.*/\.m3u8/')

while true;do
str=$(busybox ps | grep ffmpeg | grep -v grep | awk '{print$8}')

result1=$(echo $str | grep "${ch1}")
if [[ "$result1" != "" ]];then
	echo $ch1 Streaming succeeded
else
	ffmpeg -re -i $ch1 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/hjyyzs &
fi

result2=$(echo $str | grep "${ch2}")
if [[ "$result2" != "" ]];then
	echo $ch2 Streaming succeeded
else
	ffmpeg -re -i $ch2 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/zgzs1 &
fi

result3=$(echo $str | grep "${ch3}")
if [[ "$result3" != "" ]];then
	echo $ch3 Streaming succeeded
else
	ffmpeg -re -i $ch3 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/jjzs2 &
fi

result4=$(echo $str | grep "${ch4}")
if [[ "$result4" != "" ]];then
	echo $ch4 Streaming succeeded
else
	ffmpeg -re -i $ch4 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/yyzs3 &
fi

result5=$(echo $str | grep "${ch5}")
if [[ "$result5" != "" ]];then
	echo $ch5 Streaming succeeded
else
	ffmpeg -re -i $ch5 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/dszs4 &
fi

result6=$(echo $str | grep "${ch6}")
if [[ "$result6" != "" ]];then
	echo $ch6 Streaming succeeded
else
	ffmpeg -re -i $ch6 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/zhzs5 &
fi

result7=$(echo $str | grep "${ch7}")
if [[ "$result7" != "" ]];then
	echo $ch3 Streaming succeeded
else
	ffmpeg -re -i $ch7 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/szzs6 &
fi

result8=$(echo $str | grep "${ch8}")
if [[ "$result8" != "" ]];then
	echo $ch8 Streaming succeeded
else
	ffmpeg -re -i $ch8 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/hxzs7 &
fi

result9=$(echo $str | grep "${ch9}")
if [[ "$result9" != "" ]];then
	echo $ch9 Streaming succeeded
else
	ffmpeg -re -i $ch9 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/xgzs8 &
fi

result10=$(echo $str | grep "${ch10}")
if [[ "$result10" != "" ]];then
	echo $ch10 Streaming succeeded
else
	ffmpeg -re -i $ch10 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/mzzs9 &
fi

result11=$(echo $str | grep "${ch11}")
if [[ "$result11" != "" ]];then
	echo $ch11 Streaming succeeded
else
	ffmpeg -re -i $ch11 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/wyzs10 &
fi

result12=$(echo $str | grep "${ch12}")
if [[ "$result12" != "" ]];then
	echo $ch12 Streaming succeeded
else
	ffmpeg -re -i $ch12 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/wygb13 &
fi

result13=$(echo $str | grep "${ch13}")
if [[ "$result13" != "" ]];then
	echo $ch13 Streaming succeeded
else
	ffmpeg -re -i $ch13 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/ylgb14 &
fi

result14=$(echo $str | grep "${ch14}")
if [[ "$result14" != "" ]];then
	echo $ch14 Streaming succeeded
else
	ffmpeg -re -i $ch14 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/gsgljtgb16 &
fi

result15=$(echo $str | grep "${ch15}")
if [[ "$result15" != "" ]];then
	echo $ch15 Streaming succeeded
else
	ffmpeg -re -i $ch15 -ar 22050 -threads 1 -ac 1 -f mp3 icecast://source:hackme@$LAN:8001/xczs17 &
fi

done
