#!/bin/sh /etc/rc.common

# Startup script
# Copyright (C) 2015 OpenWrt.org
 
USE_PROCD=1

start_service() {

	procd_open_instance
	procd_set_param command sh /etc/m3u8mp3.sh
	procd_set_param respawn
	procd_close_instance
}
